# Use a lightweight Node.js base image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if exists) to install dependencies
COPY package*.json ./

# Install dependencies 
RUN npm ci --only=production

# Copy the rest of the application source code
COPY . .

# Build the React app for production
RUN npm run build

# Expose the port your application will run on
EXPOSE 3000

# Start the application using the production server
CMD ["npm", "run", "preview"]
